//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiControleMedico {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApiControleMedico.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lissandra Cavalheiro Maioli;NAO MARCAR;01/11/2019 07:00;Consulta;-;Particular;NÆo confirmado;NÇO;-
        ///Sharon Moura Reisdorfer;MARINA KOPPE SOARES;01/11/2019 08:15;Consulta;-;marco sa£de;Finalizado;NÇO;
        ///Sharon Moura Reisdorfer;MICHELE SCHEER;01/11/2019 08:20;Consulta;-;unimed federa‡ƒo;Finalizado;NÇO;-
        ///Sharon Moura Reisdorfer;MILENA MENEGAZ;01/11/2019 08:30;Consulta;-;UNIMED NORDESTE;Finalizado;NÇO;
        ///Sharon Moura Reisdorfer;MARILIZA GAMBATO;01/11/2019 08:30;Consulta;-;UNIMED NORDESTE;Finalizado;SIM;
        ///Fernand [rest of string was truncated]&quot;;.
        /// </summary>
        public static string agendas_novembro_importacao {
            get {
                return ResourceManager.GetString("agendas_novembro_importacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acupuntura                                    ;
        ///Alergia e imunologia                          ;
        ///Anestesiologia                                ;
        ///Angiologia                                    ;
        ///Cancerologia                                  ;
        ///Cardiologia                                   ;
        ///Cirurgia cardiovascular                       ;
        ///Cirurgia da mão                               ;
        ///Cirurgia de cabeça e pescoço                  ;
        ///Cirurgia do aparelho digestivo                ;
        ///Cirurgia geral         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string especialidades {
            get {
                return ResourceManager.GetString("especialidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIÇÃO;TIPO;DIAS;
        ///DINHEIRO;1;1;
        ///CARTÃO À VISTA;1;1
        ///CARTÃO À PRAZO;2;30.
        /// </summary>
        public static string formaDePagamento {
            get {
                return ResourceManager.GetString("formaDePagamento", resourceCulture);
            }
        }
    }
}
